# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: build-cv
on:
  push:
    branches: 
      - main
      - en-wp
      - pt-br
      - pt-br-wp

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      containerUser: ${{ steps.get-user.outputs.containerUser }}
    steps:
      - id: get-user
        run: echo "::set-output name=containerUser::`id -u`:`id -g`"

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    needs: configure
    container: 
      image: ricardoerikson/cv:latest
      options: --user ${{ needs.configure.outputs.containerUser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Build PDF
        run: make build
      - name: Commit PDF
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
          git add dist/*.pdf
          git commit -m "update file"
          git push origin ${GITHUB_REF##*/}
      - name: Release and deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.AUTHOR_EMAIL }}
        run: npx semantic-release
